name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        
        ### Configure DETECT environment variables
        env:
          # DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_NAME: test-action2
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
         
          ### SCANNING: Optional fields
          detect_args: --blackduck.trust.cert=true --detect.accuracy.required=NONE --detect.excluded.directories=.git,.github
          # blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackducksca_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackducksca_prcomment_enabled: true 
          # github_token: ${{ secrets.GH_PAT_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          # blackducksca_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
          # blackducksca_upload_sarif_report: true  # Upload Black Duck SARIF report in GitHub Advanced Security tab
